// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDojYdZd3sOQgA5FRSnIapZCQvdm_I2P6U',
    appId: '1:342532696198:web:2ccd13d81117edb24d0907',
    messagingSenderId: '342532696198',
    projectId: 'daleel-8028d',
    authDomain: 'daleel-8028d.firebaseapp.com',
    storageBucket: 'daleel-8028d.appspot.com',
    measurementId: 'G-BTB0123X85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnkUH4hZ7u2L8zJPVzQZdBTx-Z9GmMO1Y',
    appId: '1:342532696198:android:0cd0d595bdf028124d0907',
    messagingSenderId: '342532696198',
    projectId: 'daleel-8028d',
    storageBucket: 'daleel-8028d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZWnBUjzXdA5NomNgsBU9yavmiZF433R8',
    appId: '1:342532696198:ios:7d4ee50c67846ff64d0907',
    messagingSenderId: '342532696198',
    projectId: 'daleel-8028d',
    storageBucket: 'daleel-8028d.appspot.com',
    iosBundleId: 'com.example.daleel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZWnBUjzXdA5NomNgsBU9yavmiZF433R8',
    appId: '1:342532696198:ios:687075ea12f94e954d0907',
    messagingSenderId: '342532696198',
    projectId: 'daleel-8028d',
    storageBucket: 'daleel-8028d.appspot.com',
    iosBundleId: 'com.example.daleel.RunnerTests',
  );
}
